### ISSUE TITLE
Better installation instructions

### ISSUE THREAD

**Issue by JJ** [alvarohurtado84/mentoring_manager#1]
I tried to run this using the (now called) INSTALL instructions. I think django is missing, but I don't remember how to install it (pip? easy_install?)

Not clear why you use the virtual environment, either, but that worked.

**Comment by hhkaos** [comment]
Hi JJ, I have just updated a little bit the install instructions in the README file:
https://github.com/alvarohurtado84/mentoring_manager

Cheers

**Comment by JJ** [comment]
A bit better, but I don't have the directory ~/.virtualenvs and it's not clear why you need that. The following instruction works. I'm following it and checking it.

**Comment by JJ** [comment]
No, the rest does not work either since ~/.virtualenvs does not exist.

**Comment by alvarohurtado84** [comment]
Ok. I have just removed the virtualenvs things. It wasn't helping actually. And updated the Install Instruction, much easier.
