### ISSUE TITLE
Don't forget to select a license. 

### ISSUE THREAD

**Issue by JJ** [alvarohurtado84/mentoring_manager#2]
It should be on the main dir and then attached to all files. We could use this issue to discuss with @hhkaos which one would be the best.

**Comment by hhkaos** [comment]
What do you think about using Affero GPL v3? http://www.fsf.org/licensing/licenses/agpl-3.0.html

This is the one we used in GeoRemindMe.

**Comment by JJ** [comment]
It's probably OK.

2013/5/25 RaulJimenezOrtega notifications@github.com

> What do you think about using Affero GPL v3?
> http://www.fsf.org/licensing/licenses/agpl-3.0.html
> 
> This is the one we used in GeoRemindMe.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alvarohurtado84/mentoring_manager/issues/2#issuecomment-18445715
> .

## 

JJ
