### ISSUE TITLE
Publish in GitHub pages

### ISSUE THREAD

**Issue by JJ** [alvarohurtado84/mentoring_manager#4]
I just found myself how to do it, I can set it up if you want... Also hook it up with Twitter.

**Comment by hhkaos** [comment]
Great. It is creating an specific branch called gh-pages,right? I did it
here:
http://hhkaos.github.io/responsive (the course I'm creating in floqq)

---

Raúl Jiménez Ortega http://www.rauljimenez.info/perfil-profesional
_GeoRemindMe http://www.georemind.com, a whole world of recommendations
to be discovered._
GeoRemindMe!

_Contact_
Urgent contact: P_lease call me at +34 652 38 43 50 *
Chat/IM *:_ _hhkaos at google (gtalk)_ | _kaos_cs (skype)_
Social networks:
http://www.linkedin.com/pub/dir/raul/jimenez%20ortega
http://www.facebook.com/hhkaos
  http://www.twitter.com/raul_en
http://www.xing.com/profile/Raul_JimenezOrtega

**Comment by JJ** [comment]
Yep; you can generate them automatically from starters and then do some
more stuff for re-publishing automatically every time something changes. In
Perl, of course: https://github.com/JJ/hoborg/blob/master/apps/git-hooks.pl

2013/5/26 RaulJimenezOrtega notifications@github.com

> Great. It is creating an specific branch called gh-pages,right? I did it
> here:
> http://hhkaos.github.io/responsive (the course I'm creating in floqq)
> 
> ---
> 
> Raúl Jiménez Ortega http://www.rauljimenez.info/perfil-profesional
> _GeoRemindMe http://www.georemind.com, a whole world of recommendations
> to be discovered._
> GeoRemindMe!
> 
> _Contact_
> Urgent contact: P_lease call me at +34 652 38 43 50 *
> Chat/IM *:_ _hhkaos at google (gtalk)_ | _kaos_cs (skype)_
> Social networks:
> http://www.linkedin.com/pub/dir/raul/jimenez%20ortega
> http://www.facebook.com/hhkaos
> http://www.twitter.com/raul_en
> http://www.xing.com/profile/Raul_JimenezOrtega
> 
> On Sun, May 26, 2013 at 7:05 PM, Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
> 
> > I just found myself how to do it, I can set it up if you want... Also
> > hook
> > it up with Twitter.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/alvarohurtado84/mentoring_manager/issues/4>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alvarohurtado84/mentoring_manager/issues/4#issuecomment-18466956
> .

## 

JJ

**Comment by hhkaos** [comment]
Which kind of website are going going to publish there? A page with
information about what is this project and how is the platform coded?
Because we can not use it to host the django app right?

---

Raúl Jiménez Ortega http://www.rauljimenez.info/perfil-profesional
_GeoRemindMe http://www.georemind.com, a whole world of recommendations
to be discovered._
GeoRemindMe!

_Contact_
Urgent contact: P_lease call me at +34 652 38 43 50 *
Chat/IM *:_ _hhkaos at google (gtalk)_ | _kaos_cs (skype)_
Social networks:
http://www.linkedin.com/pub/dir/raul/jimenez%20ortega
http://www.facebook.com/hhkaos
  http://www.twitter.com/raul_en
http://www.xing.com/profile/Raul_JimenezOrtega

**Comment by JJ** [comment]
Basically the READMEs and links to the code. You can add anything you want,
but you can't host any app.

2013/5/27 RaulJimenezOrtega notifications@github.com

> Which kind of website are going going to publish there? A page with
> information about what is this project and how is the platform coded?
> Because we can not use it to host the django app right?
> 
> ---
> 
> Raúl Jiménez Ortega http://www.rauljimenez.info/perfil-profesional
> _GeoRemindMe http://www.georemind.com, a whole world of recommendations
> to be discovered._
> GeoRemindMe!
> 
> _Contact_
> Urgent contact: P_lease call me at +34 652 38 43 50 *
> Chat/IM *:_ _hhkaos at google (gtalk)_ | _kaos_cs (skype)_
> Social networks:
> http://www.linkedin.com/pub/dir/raul/jimenez%20ortega
> http://www.facebook.com/hhkaos
> http://www.twitter.com/raul_en
> http://www.xing.com/profile/Raul_JimenezOrtega
> 
> On Sun, May 26, 2013 at 8:09 PM, Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
> 
> > Yep; you can generate them automatically from starters and then do some
> > more stuff for re-publishing automatically every time something changes.
> > In
> > Perl, of course:
> > https://github.com/JJ/hoborg/blob/master/apps/git-hooks.pl
> > 
> > 2013/5/26 RaulJimenezOrtega notifications@github.com
> > 
> > > Great. It is creating an specific branch called gh-pages,right? I did
> > > it
> > > here:
> > > http://hhkaos.github.io/responsive (the course I'm creating in floqq)
> > 
> > ---
> > 
> > > Raúl Jiménez Ortega http://www.rauljimenez.info/perfil-profesional
> > > _GeoRemindMe http://www.georemind.com, a whole world of
> > > recommendations
> > > to be discovered._
> > > GeoRemindMe!
> > > 
> > > _Contact_
> > > Urgent contact: P_lease call me at +34 652 38 43 50 *
> > > Chat/IM *:_ _hhkaos at google (gtalk)_ | _kaos_cs (skype)_
> > > Social networks:
> > > http://www.linkedin.com/pub/dir/raul/jimenez%20ortega
> > > http://www.facebook.com/hhkaos
> > > http://www.twitter.com/raul_en
> > > http://www.xing.com/profile/Raul_JimenezOrtega
> > > 
> > > On Sun, May 26, 2013 at 7:05 PM, Juan Julián Merelo Guervós <
> > > notifications@github.com> wrote:
> > > 
> > > > I just found myself how to do it, I can set it up if you want...
> > > > Also
> > > > hook
> > > > it up with Twitter.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/alvarohurtado84/mentoring_manager/issues/4>
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/alvarohurtado84/mentoring_manager/issues/4#issuecomment-18466956>
> > 
> > > .
> > 
> > ## 
> > 
> > JJ
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/alvarohurtado84/mentoring_manager/issues/4#issuecomment-18467012>
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alvarohurtado84/mentoring_manager/issues/4#issuecomment-18493063
> .

## 

JJ
